services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: photo_user
      POSTGRES_PASSWORD: photo-map
      POSTGRES_DB: photo_route
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U photo_user -d photo_route"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "80:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://photo_user:photo-map@db:5432/photo_route
    volumes:
      - ./uploads:/app/uploads
    command: sh -c "python -c 'import asyncio; from app.main import init_models; asyncio.run(init_models())' && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always

volumes:
  postgres_data: